### PR TITLE
Use of AndroidX instead of 'com.android.support' package

### PR DESCRIPTION
**Pull request by yairopro**

### CODE REVIEW

**Comment by yairopro** [comment]
Solve #94

**Comment by yairopro** [comment]
Please @Agontuk have a look on this PR.
Only 3 lines have changed.
It upgrades the project to use androidX instead of android.support.

**Comment by Agontuk** [comment]
I already have this change in another branch. But it's currently not needed as project runs fine without it. Can you try `npx jetify` and see if it solves your issue ?

**Comment by yairopro** [comment]
Thanks a lot. It has indeed solved the issue.
Do you want me to I close this PR, since the update is in one of your branch already ?

**Comment by Agontuk** [comment]
No need, I'll close it :)

**Pull request closed without merging**
